certSecretCount: 1

syncNodeInfoInterval: 15

volumeNamePrefix: csivol

snapNamePrefix: csi-snap

maxUnityVolumesPerNode: 0

allowRWOMultiPodAccess: "false"

imagePullPolicy: IfNotPresent

controllerCount: 2

controller:
  nodeSelector:

  tolerations:


podmon:
  enabled: false
  image:

images:
  driver: dellemc/csi-unity:v1.5.0

  attacher: k8s.gcr.io/sig-storage/csi-attacher:v3.1.0

  provisioner: k8s.gcr.io/sig-storage/csi-provisioner:v2.1.0

  snapshotter: k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3

  registrar: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.1.0

  resizer:  quay.io/k8scsi/csi-resizer:v1.1.0
